name: binder_env
channels:
- defaults
dependencies:
- pandas=1.5.3
- python=3.9.16
- pip
- pip:
  - tensorboard==2.10.1
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorflow==2.10.1
  - tensorflow-estimator==2.10.0
  - tensorflow-probability==0.17.0
  - numpy==1.24.2
  - keras==2.10.0
  - scikit-learn==1.2.1
  - matplotlib==3.6.3
  - matplotlib-inline==0.1.6
  - seaborn==0.12.2
  - scipy==1.10.0
  - protobuf==3.19.6
